sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t joshualing/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true joshualing/docker-react npm run test
